import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { JsonFilter } from "../../util/JsonFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { ClientWhereUniqueInput } from "../client/ClientWhereUniqueInput";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { OwnerWhereUniqueInput } from "../owner/OwnerWhereUniqueInput";

export type UsersWhereInput = {
  active?: BooleanNullableFilter;
  address?: StringNullableFilter;
  addressComplement?: StringNullableFilter;
  addresses?: JsonFilter;
  appointmentsTotal?: IntNullableFilter;
  cardId?: StringNullableFilter;
  cash?: BooleanNullableFilter;
  cheque?: BooleanNullableFilter;
  city?: StringNullableFilter;
  client?: ClientWhereUniqueInput;
  cnpj?: StringNullableFilter;
  complement?: StringNullableFilter;
  confirmedEmail?: BooleanNullableFilter;
  coord?: JsonFilter;
  cpf?: StringNullableFilter;
  createdById?: StringNullableFilter;
  creditcard?: BooleanNullableFilter;
  debitcard?: BooleanNullableFilter;
  distance?: FloatNullableFilter;
  email?: StringNullableFilter;
  firstName?: StringNullableFilter;
  globalId?: StringNullableFilter;
  id?: StringFilter;
  isActive?: BooleanNullableFilter;
  isCash?: BooleanNullableFilter;
  isCheque?: BooleanNullableFilter;
  isConfirmedEmail?: BooleanNullableFilter;
  isCreditCard?: BooleanNullableFilter;
  isDebitCard?: BooleanNullableFilter;
  isPix?: BooleanNullableFilter;
  isSendedEmail?: BooleanNullableFilter;
  isTransferBank?: BooleanNullableFilter;
  lastName?: StringNullableFilter;
  locationCoord?: JsonFilter;
  myOwnerId?: StringNullableFilter;
  name?: StringNullableFilter;
  nextPlan?: StringNullableFilter;
  owner?: OwnerWhereUniqueInput;
  password?: StringNullableFilter;
  payDay?: StringNullableFilter;
  paymentDay?: StringNullableFilter;
  phone?: StringNullableFilter;
  photoId?: StringNullableFilter;
  photoUrl?: StringNullableFilter;
  pix?: BooleanNullableFilter;
  plan?: StringNullableFilter;
  profilePhotoUrl?: StringNullableFilter;
  role?: StringNullableFilter;
  sendedEmail?: BooleanNullableFilter;
  serviceOptions?: JsonFilter;
  totalAppointments?: IntNullableFilter;
  transferbank?: BooleanNullableFilter;
  travelDistance?: FloatNullableFilter;
  uf?: StringNullableFilter;
  userAddress?: StringNullableFilter;
  userAddresses?: JsonFilter;
  userCardId?: StringNullableFilter;
  userCity?: StringNullableFilter;
  userClientId?: StringNullableFilter;
  userCnpj?: StringNullableFilter;
  userCpf?: StringNullableFilter;
  userEmail?: StringNullableFilter;
  userGlobalId?: StringNullableFilter;
  userMyOwnerId?: StringNullableFilter;
  userNextPlan?: StringNullableFilter;
  userOwnerId?: StringNullableFilter;
  userPassword?: StringNullableFilter;
  userPhone?: StringNullableFilter;
  userPhotoId?: StringNullableFilter;
  userPlan?: StringNullableFilter;
  userRole?: StringNullableFilter;
  userServiceOptions?: JsonFilter;
  userUf?: StringNullableFilter;
};
