import { InputJsonValue } from "../../types";
import { ClientWhereUniqueInput } from "../client/ClientWhereUniqueInput";
import { OwnerWhereUniqueInput } from "../owner/OwnerWhereUniqueInput";

export type UsersCreateInput = {
  active?: boolean | null;
  address?: string | null;
  addressComplement?: string | null;
  addresses?: InputJsonValue;
  appointmentsTotal?: number | null;
  cardId?: string | null;
  cash?: boolean | null;
  cheque?: boolean | null;
  city?: string | null;
  client?: ClientWhereUniqueInput | null;
  cnpj?: string | null;
  complement?: string | null;
  confirmedEmail?: boolean | null;
  coord?: InputJsonValue;
  cpf?: string | null;
  createdById?: string | null;
  creditcard?: boolean | null;
  debitcard?: boolean | null;
  distance?: number | null;
  email?: string | null;
  firstName?: string | null;
  globalId?: string | null;
  isActive?: boolean | null;
  isCash?: boolean | null;
  isCheque?: boolean | null;
  isConfirmedEmail?: boolean | null;
  isCreditCard?: boolean | null;
  isDebitCard?: boolean | null;
  isPix?: boolean | null;
  isSendedEmail?: boolean | null;
  isTransferBank?: boolean | null;
  lastName?: string | null;
  locationCoord?: InputJsonValue;
  myOwnerId?: string | null;
  name?: string | null;
  nextPlan?: string | null;
  owner?: OwnerWhereUniqueInput | null;
  password?: string | null;
  payDay?: string | null;
  paymentDay?: string | null;
  phone?: string | null;
  photoId?: string | null;
  photoUrl?: string | null;
  pix?: boolean | null;
  plan?: string | null;
  profilePhotoUrl?: string | null;
  role?: string | null;
  sendedEmail?: boolean | null;
  serviceIds?: Array<"Option1">;
  serviceOptions?: InputJsonValue;
  totalAppointments?: number | null;
  transferbank?: boolean | null;
  travelDistance?: number | null;
  uf?: string | null;
  userAddress?: string | null;
  userAddresses?: InputJsonValue;
  userCardId?: string | null;
  userCity?: string | null;
  userClientId?: string | null;
  userCnpj?: string | null;
  userCpf?: string | null;
  userEmail?: string | null;
  userGlobalId?: string | null;
  userMyOwnerId?: string | null;
  userNextPlan?: string | null;
  userOwnerId?: string | null;
  userPassword?: string | null;
  userPhone?: string | null;
  userPhotoId?: string | null;
  userPlan?: string | null;
  userRole?: string | null;
  userServiceOptions?: InputJsonValue;
  userUf?: string | null;
};
