import { JsonValue } from "type-fest";
import { Client } from "../client/Client";
import { Owner } from "../owner/Owner";

export type Users = {
  active: boolean | null;
  address: string | null;
  addressComplement: string | null;
  addresses: JsonValue;
  appointmentsTotal: number | null;
  cardId: string | null;
  cash: boolean | null;
  cheque: boolean | null;
  city: string | null;
  client?: Client | null;
  cnpj: string | null;
  complement: string | null;
  confirmedEmail: boolean | null;
  coord: JsonValue;
  cpf: string | null;
  createdAt: Date;
  createdById: string | null;
  creditcard: boolean | null;
  debitcard: boolean | null;
  distance: number | null;
  email: string | null;
  firstName: string | null;
  globalId: string | null;
  id: string;
  isActive: boolean | null;
  isCash: boolean | null;
  isCheque: boolean | null;
  isConfirmedEmail: boolean | null;
  isCreditCard: boolean | null;
  isDebitCard: boolean | null;
  isPix: boolean | null;
  isSendedEmail: boolean | null;
  isTransferBank: boolean | null;
  lastName: string | null;
  locationCoord: JsonValue;
  myOwnerId: string | null;
  name: string | null;
  nextPlan: string | null;
  owner?: Owner | null;
  password: string | null;
  payDay: string | null;
  paymentDay: string | null;
  phone: string | null;
  photoId: string | null;
  photoUrl: string | null;
  pix: boolean | null;
  plan: string | null;
  profilePhotoUrl: string | null;
  role: string | null;
  sendedEmail: boolean | null;
  serviceIds?: Array<"Option1">;
  serviceOptions: JsonValue;
  totalAppointments: number | null;
  transferbank: boolean | null;
  travelDistance: number | null;
  uf: string | null;
  updatedAt: Date;
  userAddress: string | null;
  userAddresses: JsonValue;
  userCardId: string | null;
  userCity: string | null;
  userClientId: string | null;
  userCnpj: string | null;
  userCpf: string | null;
  userEmail: string | null;
  userGlobalId: string | null;
  userMyOwnerId: string | null;
  userNextPlan: string | null;
  userOwnerId: string | null;
  userPassword: string | null;
  userPhone: string | null;
  userPhotoId: string | null;
  userPlan: string | null;
  userRole: string | null;
  userServiceOptions: JsonValue;
  userUf: string | null;
};
